'use strict';

/**
 * Converts ico.jpeg → icon.png (256x256) → icon.ico
 * Uses Jimp v1.x API (the installed version)
 */

const fs   = require('fs');
const path = require('path');

const jpegSrc = path.resolve(__dirname, 'electron/assets/ico.jpeg');
const pngOut  = path.resolve(__dirname, 'electron/assets/icon_from_jpeg.png');
const icoOut  = path.resolve(__dirname, 'electron/assets/icon.ico');

console.log('Source JPEG:', jpegSrc);
console.log('Exists:', fs.existsSync(jpegSrc));

async function main() {
  // ─── Jimp v1.x API ───────────────────────────────────────────
  const { Jimp } = require('jimp');

  console.log('Reading JPEG with Jimp v1.x...');
  const image = await Jimp.read(jpegSrc);
  
  console.log(`Original size: ${image.width}x${image.height}`);

  // تغيير الحجم إلى 256x256
  image.resize({ w: 256, h: 256 });
  console.log(`Resized to: ${image.width}x${image.height}`);

  // حفظ كـ PNG
  await image.write(pngOut);
  console.log('PNG written:', pngOut);

  // التحقق من صحة PNG
  const pngBuf = fs.readFileSync(pngOut);
  const isPng = pngBuf[0] === 0x89 && pngBuf[1] === 0x50 && pngBuf[2] === 0x4E && pngBuf[3] === 0x47;
  console.log('PNG valid signature:', isPng, '| Header hex:', pngBuf.slice(0, 8).toString('hex'));
  console.log('PNG size:', pngBuf.length, 'bytes');

  if (!isPng) {
    throw new Error('PNG file generated by Jimp has invalid header!');
  }

  // ─── تحويل PNG → ICO ────────────────────────────────────────
  console.log('\nConverting PNG to ICO...');
  const pngToIco = require('png-to-ico');
  const fn = pngToIco.default || pngToIco;

  const icoBuf = await fn([pngOut]);
  fs.writeFileSync(icoOut, icoBuf);
  
  // نسخ لجميع مواقع الأيقونات
  const alxIco = path.resolve(__dirname, 'electron/assets/alx.ico');
  fs.copyFileSync(icoOut, alxIco);

  // التحقق من ICO
  const icoHeader = fs.readFileSync(icoOut).slice(0, 6);
  const reserved = icoHeader.readUInt16LE(0);
  const type     = icoHeader.readUInt16LE(2);
  const count    = icoHeader.readUInt16LE(4);

  console.log('\n✅ ICO created successfully!');
  console.log('   Size   :', icoBuf.length, 'bytes');
  console.log('   Reserved:', reserved, '(must be 0)');
  console.log('   Type    :', type, '(must be 1)');
  console.log('   Images  :', count);
  console.log('   Saved to:', icoOut);
  console.log('   Copied  :', alxIco);

  if (reserved !== 0 || type !== 1) {
    throw new Error('ICO file has invalid header values!');
  }

  console.log('\n🎉 All done! Ready to build EXE.');
}

main().catch(err => {
  console.error('\n❌ ERROR:', err.message);
  process.exit(1);
});
